## SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev>
##
## SPDX-License-Identifier: MIT

[run]
go = "1.24"
tests = true

[linters]
enable = ["stylecheck", "whitespace", "containedctx", "contextcheck", "decorder",
    "errname", "errorlint", "gofmt", "gofumpt"]
