# SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "scscrypter"
SPDX-PackageSupplier = "Winni Neessen <winni@neessen.dev>"
SPDX-PackageDownloadLocation = "https://github.com/wneessen/scs-crypter"

[[annotations]]
path = ["flake.nix"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Winni Neessen <winni@neessen.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["flake.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Winni Neessen <winni@neessen.dev>"
SPDX-License-Identifier = "MIT"
